### ISSUE TITLE
Release for Kinetic

### ISSUE THREAD

**Issue by jvgomez** [ros-visualization/rviz_animated_view_controller#5]
Hi, I am wondering if you are considering releasing this package for ROS Kinetic. Thanks.

**Comment by rafonki** [comment]
As an additional note, compilation under Kinetic works but the CMakeLists.txt should add the following line:

`add_dependencies(${PROJECT_NAME} ${view_controller_msgs_EXPORTED_TARGETS})`

I didn't do a PR because there is not `kinectic-devel` branch yet.

**Comment by RValner** [comment]
Hi,

It seems that there is some inconsistencies with Qt versions. So here is what we at NRG lab found out:
Initial observations:

* initially without any changes in the cmakelists file, rviz throws a seg fault when loading the plugin without any further info. just gone
* when ["rviz plugin tutorials" example](https://github.com/ros-visualization/visualization_tutorials/blob/kinetic-devel/rviz_plugin_tutorials/CMakeLists.txt) cmakelists is used, an error pops up saying:
`Failed to load library /home/andrew/repositories/motoman/devel/lib/librviz_animated_view_controller.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/andrew/repositories/motoman/devel/lib/librviz_animated_view_controller.so: undefined symbol: _ZTVN29rviz_animated_view_controller22AnimatedViewControllerE)`

After some debugging:

* In CMakeLists.txt, the "rviz_QT_VERSION" prints out version which is +5.x.x, which is ok since ...
* ... rviz binary on kinetic is by default compiled against qt5 and therefore qt5 must be used when compiling your rviz plugin.
* Rviz plugin tutorials is fancy and checks the version of qt but fails on using either of them afterwards. By failing I mean, that incorrect cmake variables are used and/or set (variables that point out where include files and libs are located)
* Not sure about that one but it seems that before qt5, these "QT_INCLUDE_DIR" contained paths to all qt related stuff. Now with qt5, user has to specify what kind of "stuff" is needed. For example if its looking for "QT_INCLUDE_DIR" or "QT_USE_FILE" (magical qt specific cmake variables for qt widget, core, gui, etc., directories) it gets nothing.
* Now finally, when the plugin was built with qt4, everything is fine until rviz loads the plugin. It will get something completely different than its expecting and rviz crashes (some internal magic due to version differences: "v4 for dynamically loaded plugin" vs "v5 rviz binary")

These are just the things we observed, without knowing the specific inner clockwork of cmake/qmake/find_package magic. But we are quite sure, that "rviz plugin tutorials" cmakelists
is unfinished or broken and kinda spreads the chaos. SO as a quick fix in kinetic, you:

* Set the include directories manually, for example: if your plugin needs qtcore and qt widgets: "set(QT_INCLUDE_DIRS ${Qt5Core_INCLUDE_DIRS} ${Qt5Widgets_INCLUDE_DIRS} )" and use it in the include_directories() cmake function: "include_directories(include ${catkin_INCLUDE_DIRS} otherDir1 otherDir2 )". Again, qt4 had this nice variable "QT_INCLUDE_DIR" that already contained all the necessary things but with qt5, this thing either does not exist, has a different name or requires some specific cmake function to be called out beforehand. Dunno.
* use "qt5_wrap_cpp(MOC_FILES bla bla)" instead of "set(CMAKE_AUTOMOC ON)". MOC is a magic within a witchcraft mixed with fairy tales that makes all [hannibal's plans come together](http://s2.quickmeme.com/img/a9/a9ed842f739e930dc8e9340bafbbaeaf77994c50c74fc6a86b046b54cb9b2c59.jpg). We did not dig deep, but this gives a short overview: http://doc.qt.io/qt-4.8/moc.html . The use of either "automoc" or "qt5_wrap_cpp()" depends on the version of the cmake: http://doc.qt.io/qt-5/cmake-manual.html

Thats about it. You can find the rviz_animated_view_controller for kinetic here: https://github.com/UTNuclearRoboticsPublic/rviz_animated_view_controller

I hope this info helps.

**Comment by Sagexs** [comment]
here is the cmakefile that works for me under ros melodic
[CMakeLists.txt](https://github.com/ros-visualization/rviz_animated_view_controller/files/4735524/CMakeLists.txt)

**Comment by flynneva** [comment]
closing this as [this package is released for kinetic](https://index.ros.org/p/rviz_animated_view_controller/github-ros-visualization-rviz_animated_view_controller/#kinetic) and kinetic is EOL
